version: '3.8'

services:
  # The Web App
  rag-app:
    image: your_dockerhub_username/rag-ai-suite:latest
    container_name: rag_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
    depends_on:
      - ollama-service

  # The Brain (Ollama)
  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama_backend
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data: